Restaurants.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Restaurants.MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Restaurants.MVC/Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dubuche.DAL;
using Dubuche.BL;
using NLog;

namespace Restaurants.MVC.Controllers
{
    public class RestaurantController : Controller
    {
        private Logger log;

        //Search
        public ActionResult Search(string Name)
        {
            var bl = new Dubuche.BL.RestaurantCRUD();
            
            List<Restaurant> newRestList = new List<Restaurant>();
            newRestList = bl.GetAllRestaurants();
            return View (RestaurantSearch.Lookup (newRestList, Name));
        }

        public ActionResult Sort(string sort)
        {

            var bl = new Dubuche.BL.RestaurantCRUD();
            var list = Dubuche.BL.RestaurantCRUD.Casting(bl.GetAllRestaurants());
            var sortedList = list;
            //var sortedList = RestaurantSort.AlphaSorting(Dubuche.BL.RestaurantCRUD.Casting(list));
            //var downSortedList = RestaurantSort.BetaSorting(Dubuche.BL.RestaurantCRUD.Casting(list));
            //var ratedSortedList = RestaurantSort.AvgRatingSort(Dubuche.BL.RestaurantCRUD.Casting(list));
            //var topThreeSorted = RestaurantSort.AvgRatingSort(Dubuche.BL.RestaurantCRUD.Casting(list));

            try
            {
                if (sort == "byName")
                {
                    sortedList = RestaurantSort.AlphaSorting(list);                 
                }
                else if (sort == "byRating")
                {
                    sortedList = RestaurantSort.AvgRatingSort(list);
                }
                else if (sort == "topThree")
                {
                    sortedList = RestaurantSort.AvgRatingSort(list.Take(3).ToList());
                }
                return View(sortedList);

            }
            catch
            {
                log = LogManager.GetLogger("mistakes");
                return RedirectToAction("Index");
            }

        }

        // GET: Restaurant
        public ActionResult Index()
        {
            var bl = new Dubuche.BL.RestaurantCRUD();
            //var list = bl.GetAllRestaurants();

            return View(bl.GetAllRestaurants());

            //List<Restaurant> A
        }

        // GET: Restaurant/Details/5
        public ActionResult Details(int id)
        {
            var bl = new Dubuche.BL.RestaurantCRUD();
            var x = bl.GetRestaurantById(id);
            return View(x);
        }

        // GET: Restaurant/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Restaurant/Create
        [HttpPost]
        public ActionResult Create(Restaurant restaurant)
        {
            try
            {
                // TODO: Add insert logic here
                var bl = new Dubuche.BL.RestaurantCRUD();
                bl.CreateRestaurant(restaurant);
                
                return RedirectToAction("Index");
            }
            catch
            {
                log = LogManager.GetLogger("mistakes");
                return View();
            }
        }

        // GET: Restaurant/Edit/5
        public ActionResult Edit(int id)
        {
            var bl = new Dubuche.BL.RestaurantCRUD();
            var x = bl.GetRestaurantById(id);
            return View(x);
        }

        // POST: Restaurant/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Restaurant restaurant2)
        {
            try
            {
                // TODO: Add update logic here
                var bl = new Dubuche.BL.RestaurantCRUD();
                bl.UpdateRestaurant(restaurant2);
                return RedirectToAction("Index");
            }
            catch
            {
                log = LogManager.GetLogger("mistakes");
                return View();
            }
        }

        // GET: Restaurant/Delete/5
        public ActionResult Delete(int id)
        {
            var bl = new Dubuche.BL.RestaurantCRUD();
            //bl.DeleteRestaurantById(id);
            return View(bl.GetRestaurantById(id));
         
        }

        // POST: Restaurant/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Restaurant restaurant)
        {
            try
            {
                // TODO: Add delete logic here
                var bl = new Dubuche.BL.RestaurantCRUD();
                bl.DeleteRestaurantById(id);
                
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                log = LogManager.GetLogger("mistakes");
                log.Error($"[Restaurants Controller] [Details] Exception thrown: {e.Message}");
                return RedirectToAction("Index");
            }
        }
    }
}

Restaurants.MVC/Controllers/ReviewerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dubuche.DAL;
using Dubuche.BL;
using NLog;

namespace Restaurants.MVC.Controllers
{
    public class ReviewerController : Controller
    {
        private Logger log;

        // GET: Reviewer
        public ActionResult Index()
        {
            var bl = new Dubuche.BL.ReviewerCRUD();
            return View(bl.AllReviewers());
        }

        // GET: Reviewer/Details/5
        public ActionResult Details(int id)
        {
            var bl = new Dubuche.BL.ReviewerCRUD();
            var x = bl.DisplayRestaurantReviewersById(id);
            return View(x);
        }

        // GET: Reviewer/Create
        public ActionResult Create()
        {
            
            var bl = new Dubuche.BL.ReviewerCRUD();
            var restCrud = new Dubuche.BL.RestaurantCRUD();
            ViewBag.Rests = restCrud.GetAllRestaurants();
            return View();
        }

        // POST: Reviewer/Create
        [HttpPost]
        public ActionResult Create(Reviewer reviewer)
        {
            try
            {                
                // TODO: Add insert logic here
                var bl = new Dubuche.BL.ReviewerCRUD();
                bl.CreateReviewer(reviewer);

                return RedirectToAction("Index");
            }
            catch
            {
                log = LogManager.GetLogger("mistakes");
                return View();
            }
        }

        // GET: Reviewer/Edit/5
        public ActionResult Edit(int id)
        {
            var bl = new Dubuche.BL.ReviewerCRUD();
            var x = bl.DisplayRestaurantReviewersById(id);
            var restCrud = new Dubuche.BL.RestaurantCRUD();
            ViewBag.Rests = restCrud.GetAllRestaurants();
            return View(x);
        }

        // POST: Reviewer/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Reviewer reviewer2)
        {
            try
            {
                
                // TODO: Add update logic here
                var bl = new Dubuche.BL.ReviewerCRUD();
                bl.UpdateReviewers(reviewer2);
                return RedirectToAction("Index");
            }
            catch
            {
                log = LogManager.GetLogger("mistakes");
                return View();
            }
        }

        // GET: Reviewer/Delete/5
        public ActionResult Delete(int id)
        {
            var bl = new Dubuche.BL.ReviewerCRUD();
            return View(bl.DisplayRestaurantReviewersById(id));
        }

        // POST: Reviewer/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Reviewer reviewer)
        {
            try
            {
                // TODO: Add delete logic here
                var bl = new Dubuche.BL.ReviewerCRUD();
                bl.DeleteReviewerById(id);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                log = LogManager.GetLogger("mistakes");
                log.Error($"[Reviewer Controller] [Delete] Exception thrown: {e.Message}");
                return RedirectToAction("Index");
            }
        }
    }
}

Restaurants.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Dubuche Restaurant Reviews</h1>
    <p class="lead">This a free resource for the people of Tampa to find the <em><bold>BEST</bold></em> places to eat.</p>
    <p><a href="https://revature.com" target="_blank" class="btn btn-primary btn-lg">Let's Go! &raquo;</a></p>
</div>

<div class="row">
    @*<div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>*@
    @*<div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>*@
    @*<div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>*@
</div>

Restaurants.MVC/Views/Restaurant/Create.cshtml
@model Dubuche.DAL.Restaurant


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Restaurant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group" required>
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" } )
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Website, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Website, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Website, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Restaurants.MVC/Views/Restaurant/Delete.cshtml
@model Dubuche.DAL.Restaurant

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Restaurants.MVC/Views/Restaurant/Details.cshtml
@model Dubuche.DAL.Restaurant

<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Restaurants.MVC/Views/Restaurant/Edit.cshtml
@model Dubuche.DAL.Restaurant


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Restaurant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Website, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Website, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Website, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Restaurants.MVC/Views/Restaurant/Index.cshtml
@model IEnumerable<Dubuche.DAL.Restaurant>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<a href="/Restaurant/Sort?sort=byName" class="btn btn-default btn-toolbar">Sort By Name</a>
<a href="/Restaurant/Sort?sort=byRating" class="btn btn-default btn-toolbar">Sort By Avg. Rating</a>
<a href="/Restaurant/Sort?sort=topThree" class="btn btn-default btn-toolbar">Top 3</a>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Website)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rating)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Website)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rating)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>

Restaurants.MVC/Views/Restaurant/Index1.cshtml
@model IEnumerable<Dubuche.DAL.Restaurant>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Restaurants.MVC/Views/Restaurant/Search.cshtml
@model IEnumerable<Dubuche.DAL.Restaurant>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Website)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Website)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Restaurants.MVC/Views/Restaurant/Sort.cshtml
@model IEnumerable<Dubuche.BL.Restaurants>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<a href="/Restaurant/Sort?sort=byName" class="btn btn-default btn-toolbar">Sort By Name</a>
<a href="/Restaurant/Sort?sort=byRating" class="btn btn-default btn-toolbar">Sort By Avg. Rating</a>
<a href="/Restaurant/Sort?sort=topThree" class="btn btn-default btn-toolbar">Top 3</a>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Website)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rating)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Website)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rating)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
    }

</table>

Restaurants.MVC/Views/Restaurant/Top.cshtml
@model IEnumerable<Dubuche.DAL.Restaurant>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Restaurants.MVC/Views/Reviewer/Create.cshtml
@model Dubuche.DAL.Reviewer


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Reviewer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RestaurantId, "RestaurantId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <Select name="RestaurantId">
                    @{ foreach (var Rest in ViewBag.Rests)
                        {
                    <option value="@Rest.Id">@Rest.Name</option>
                            }
                        }

                </Select>
                @Html.ValidationMessageFor(model => model.RestaurantId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Restaurants.MVC/Views/Reviewer/Delete.cshtml
@model Dubuche.DAL.Reviewer

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reviewer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Restaurant.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restaurant.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Restaurants.MVC/Views/Reviewer/Details.cshtml
@model Dubuche.DAL.Reviewer

<div>
    <h4>Reviewer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Restaurant.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restaurant.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RestaurantId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Restaurants.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*<script src="~/Scripts/RestaurantSearch.js"></script>*@
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Restaurant Reviews", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("New Restaurants", "Create", "Restaurant")</li>
                    <li>@Html.ActionLink("All Restaurants", "Index", "Restaurant")</li>
                    <li>@Html.ActionLink("Reviewers", "Index", "Reviewer")</li>
                    @*<li>@Html.ActionLink("Search Restaurants", "Search", "Restaurants")</li>
            <li>@Html.ActionLink("Top Restaurants", "Top", "Restaurant")</li>*@
                </ul>
                <br />
               @using (Html.BeginForm("Search", "Restaurant", FormMethod.Get))
               {
                   @Html.TextBox("Name");
                   <input type="submit" value="Submit" />
               }


            @*TODO  USE HTML BEGIN FORM - forget jquery*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Dubuche Restaurant Reviews, Inc.</p>
        </footer>
    </div>

    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>


</html>